#!/bin/bash
# generate emission table on each pixel

chidir=$HOME/Dropbox/IDL/FoMo/newchiantitables/
chifile='goft_table_fe_19_1118_abco.dat'
abdir='/users/cpa/tomvd/ssw/packages/chianti/dbase/abundance/'
abfile='sun_coronal_2012_schmelz.abund'
standardabfile='sun_coronal.abund'
datadir=$HOME/fomodata/ #datadir=$HOME/shared/
#emsave='stslow_fine_adv_emis'
#infileini='stslow_fine_adv'
#outfileini='stslow_fine_adv_out'
emsave='stslow_emis'
infileini='stslow'
outfileini='stslow_out'

tstart='3'
tend='3'
tstep='1'
echo "${chidir}"
if [ "$#" -eq 1 ]; then
  reuse="$1"
src/stiefkink --reuse \
            --goftfile ${chidir}${chifile}\
            --emissionsave ${datadir}${emsave}\
            --outfileini ${datadir}${outfileini}\
            --tstart=${tstart} --tend=${tend} --tstep=${tstep}  
fi
if [ "$#" -eq 0 ]; then
src/stiefkink \
            --goftfile ${chidir}${chifile}\
            --abundfile ${abdir}${abfile}\
            --emissionsave ${datadir}${emsave}\
            --infileini ${datadir}${infileini}\
            --tstart=${tstart} --tend=${tend} --tstep=${tstep}   

fi
